services:
  app:
    build:
      context: .
    environment:
      - DATABASE_URL=mysql://root:admin@db:3306/cep_tracking
      - ALLOWED_ORIGINS=http://host.docker.internal:3001,http://host.docker.internal:5173
    ports:
      - '3000:3000'
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: cep_tracking
    ports:
      - '3306:3306'
