name: CI Pipeline

on:
  push:
    paths:
      - '**' # Trigger only on changes in this directory
    branches:
      - main
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 1
          persist-credentials: false

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Run Linter
      - name: Run Linter
        run: |
          npm install -g eslint  # Install ESLint globally
          eslint ./src  # Lint JavaScript and TypeScript files

      # Step 5: Install dependencies and run tests
      - name: Install dependencies and run tests
        run: |
          cd .
          npm install
          npm run test

      # Step 6: Log in to Docker Hub
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 7: Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t vs316/cep-tracking-api-nestjs-app:latest .
          docker push vs316/cep-tracking-api-nestjs-app:latest

      # Step 8: Restart Docker Compose Stack
      - name: Restart Docker Compose Stack
        run: |
          docker compose -f ./cep-tracking-api/docker-compose.yml pull nestjs-app
          docker compose -f ./cep-tracking-api/docker-compose.yml up -d --no-deps nestjs-app
