name: CI Pipeline

on:
  push:
    paths:
      - 'cep-tracking-api/**' # Trigger only on changes in this directory
    branches:
      - main
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  deploy:
    runs-on: self-hosted
    env:
      RUNNER_TEMP: ${{ runner.temp }}/${{ github.run_id }}
      GITHUB_WORKSPACE: ${{ runner.workspace }}/${{ github.run_id }}
      # GIT_OPTIONAL_LOCKS: 0 # Prevent file locking
    steps:
      # Step 1: Checkout the repository in a fresh folder
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: true # Ensure thorough cleanup
          fetch-depth: 1 # Shallow clone to reduce overhead
          persist-credentials: false
          path: fresh-repo # Specify a unique folder name for each checkout

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Lint the code
      - name: Run Linter
        run: |
          npm install -g eslint  # Install eslint
          eslint fresh-repo/cep-tracking-api/  # Run linting

      # Step 4: Install dependencies and run tests
      - name: Install dependencies and run tests
        working-directory: fresh-repo/cep-tracking-api
        run: |
          npm install
          npm run test

      # Step 5: Log in to Docker Hub
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 6: Build and push Docker image with new name
      - name: Build and push Docker image
        run: |
          docker build -t vs316/cep-tracking-api-nestjs-app:latest ./fresh-repo/cep-tracking-api
          docker push vs316/cep-tracking-api-nestjs-app:latest

      # Step 7: Pull new image and restart Docker Compose stack
      - name: Restart Docker Compose Stack
        run: |
          docker compose -f ./fresh-repo/cep-tracking-api/docker-compose.yml pull nestjs-app
          docker compose -f ./fresh-repo/cep-tracking-api/docker-compose.yml up -d --no-deps nestjs-app
