name: CI Pipeline

on:
  push:
    paths:
      - 'cep-tracking-api/**' # Trigger only on changes in this directory
    branches:
      - main
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # Step 1: Create a fresh directory and checkout code
      - name: Setup fresh folder for checkout
        run: |
          mkdir -p "CI Pipeline" # Create folder if not exists
          cd "CI Pipeline"       # Navigate to the new folder
          echo "Fresh folder setup complete."

      # Step 2: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4 # Use latest version
        with:
          path: 'CI Pipeline' # Checkout repository into the new folder
          clean: true # Ensure thorough cleanup
          fetch-depth: 1 # Shallow clone to reduce overhead
          persist-credentials: false

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Lint the code
      - name: Run Linter
        run: |
          cd "CI Pipeline"
          npm install -g eslint  # Install eslint
          eslint cep-tracking-api/  # Run linting

      # Step 5: Install dependencies and run tests
      - name: Install dependencies and run tests
        run: |
          cd "CI Pipeline"
          npm install
          npm run test

      # Step 6: Log in to Docker Hub
      - name: Log in to DockerHub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 7: Build and push Docker image with new name
      - name: Build and push Docker image
        run: |
          cd "CI Pipeline/cep-tracking-api"
          docker build -t vs316/cep-tracking-api-nestjs-app:latest .
          docker push vs316/cep-tracking-api-nestjs-app:latest

      # Step 8: Pull new image and restart Docker Compose stack
      - name: Restart Docker Compose Stack
        run: |
          cd "CI Pipeline/cep-tracking-api"
          docker compose pull nestjs-app
          docker compose up -d --no-deps nestjs-app
